apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: nginx    # Changed to match service selector
spec:
  containers:
    - name: app
      image: nginx
      ports:
        - containerPort: 80  # Added to expose nginx port
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"